# Generated by Django 4.2.6 on 2023-11-03 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_actualizar', models.DateTimeField(auto_now=True)),
                ('usuario', models.CharField(max_length=255)),
                ('clave', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_actualizar', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('f_nacimiento', models.DateField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weblogin.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
