# Generated by Django 4.2.6 on 2023-11-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webventa', '0005_alter_productos_imagen_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen_prod',
            field=models.ImageField(default='img/default.jpg', upload_to=''),
        ),
    ]
