# Generated by Django 4.2.6 on 2023-11-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webventa', '0006_alter_productos_imagen_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen_prod',
            field=models.CharField(default='https://cubezz.com/images/202106/goods_img/6608_P_1622689298143.jpg', max_length=500),
        ),
    ]
